---
channel: edge
addons:
  minio:
    repository: kalw/hassio-addon-seaweedfs
    target: minio
    image: ghcr.io/kalw/seaweedfs/{arch}
  ha_stats_lake:
    repository: kalw/ha-stats-lake
    target: ha_stats
    image: ghcr.io/kalw/ha_stats_lake/{arch}
