---
channel: edge
addons:
  hassio-addon-seaweedfs:
    repository: kalw/hassio-addon-seaweedfs
    target: seaweedfs
    image: ghcr.io/kalw/hassio-addon-seaweedfs/{arch}
  ha_stats_lake:
    repository: kalw/hassio-addon-stats-lake
    target: ha_stats
    image: ghcr.io/kalw/hassio-addon-stats-lake/{arch}
  hassio-addon-vault:
    repository: kalw/hassio-addon-vault
    target: vault
    image: ghcr.io/kalw/hassio-addon-vault/{arch}
