name: SeaweedFS
version: '5967698'
slug: seaweedfs
description: SeaweedFS S3-compatible distributed object storage
url: https://github.com/kalw/hassio-addon-seaweedfs
arch:
- aarch64
- amd64
init: false
ingress: true
ingress_port: 8888
map:
- share:rw
ports:
  8333/tcp: 8333
  8888/tcp: 8888
ports_description:
  8333/tcp: S3 API port
  8888/tcp: Web UI port
panel_icon: mdi:database
panel_title: SeaweedFS
options:
  data_path: /share/seaweedfs
  s3_region: us-east-1
  access_key_id: seaweedfsadmin
  secret_key: null
schema:
  data_path: str
  s3_region: str
  access_key_id: str
  secret_key: str
image: ghcr.io/kalw/seaweedfs/{arch}
