name: MinIO
version: 6fb0d44
slug: minio
description: MinIO high-performance object storage
url: https://github.com/kalw/hassio-addon-minio
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
init: false
map:
- share:rw
- ssl
webui: '[PROTO:ssl]://[HOST]:[PORT:9001]'
ports:
  9001/tcp: 9001
  9000/tcp: 9000
ports_description:
  9001/tcp: Console port
  9000/tcp: API port
panel_icon: mdi:database
panel_title: MinIO
options:
  ssl: true
  certfile: null
  keyfile: null
  data_path: /share/minio
  username: admin
  password: null
schema:
  ssl: bool
  certfile: str?
  keyfile: str?
  data_path: str
  username: str
  password: str
image: ghcr.io/kalw/minio/{arch}
