name: MinIO
version: 2e75e62
slug: minio
description: MinIO high-performance object storage
url: https://github.com/kalw/hassio-addons/tree/master/minio
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
init: false
map:
- share:rw
- ssl
webui: '[PROTO:ssl]://[HOST]:[PORT:9001]'
ports:
  9001/tcp: 9001
  9000/tcp: 9000
ports_description:
  9001/tcp: Console port
  9000/tcp: API port
panel_icon: mdi:database
panel_title: MinIO
options:
  ssl: false
  ssl_certificate: null
  ssl_key: null
  data_path: /share/minio
  username: admin
  password: null
schema:
  ssl: bool
  ssl_certificate: str?
  ssl_key: str?
  data_path: str
  username: str
  password: str
image: ghcr.io/kalw/hassio-addon-minio/${arch}
